### ISSUE TITLE
BRL based conversion inconsistency

### ISSUE THREAD

**Issue by MarceloCavalcanti21** [madisvain/exchangeratesapi#109]
Hi!

I'm using your API and really enjoying the result, by the way.

Just a detail that I realized is that when I use the BRL currency as the basis for conversion, the result is not accurate.

For example, with the base date 1/14/2021, the USD to BRL conversion is as follows:

1 USD = 5.269548004 BRL (https://api.exchangeratesapi.io/latest?base=USD)

However, I need my base to be the BRL. When I try to do the conversion based on BRL, the result is the following:

1 BRL = 0.1897695968 USD (https://api.exchangeratesapi.io/latest?base=BRL)

The ideal would be: 1 BRL = 5.269548004 USD.

Clearly, the API is dividing 1 (BRL) by 5.269548004 (USD) while it should only show 5.269548004, which is the value of the Brazilian real against the US dollar.

Could you please analyze that?

**Comment by tiagogiantini** [comment]
Hi Marcelo.
By chance, I saw this.
The API is correct because 1BRL worth around 18 cents US Dollar.
When you see a pair, like USDBRL or EURBRL, you will get the value that the first currency buys of the second one.
So 1 USD buys 5.26 BRL, 1 EUR buys 6.6421 BRL.
You can use BRL as Base, and then divide the values on other currencies by 1 to get BRL value.
Example:
1 BRL = 0.2254 CAD. How much 1CAD worth in BRL? Just divide 1 by 0.2254, so 1 CAD worths 4.4365BRL

**Comment by MarceloCavalcanti21** [comment]
Thank's!
